[baseConfig]
	logPath="ctp"
    mdhost= "tcp://180.168.146.187:10211"  # 期货行情地址 10211    全天  10131
    tdhost= "tcp://180.168.146.187:10201"   # 期货交易地址 10201   全天 10130
    broker= "9999"      #券商ID
    user= "235096"      # 资金账号
    pwd= "Junge@265045" #密码
    appid= "simnow_client_test" #appid
    authcode= '0000000000000000' #authcode
    subSymbol= ["au2506"] #期货交易标的

[db]
    host="rm-bp1l09swp665a10naro.mysql.rds.aliyuncs.com"
    user="test_quant"
    pwd="ASDzxc!%40#"  # 实际为ASDzxc!@#
    charset="utf8"
	db="quant"
	table="child"
	
[zmq]
	subpubPort="tcp://127.0.0.1:20001"
    topic="market"
    reqrspPort="tcp://127.0.0.1:30001"