[baseConfig]
    path= "D:\\MT5\\ICMT5\\terminal64.exe"
    host= "ICMarketsSC-Demo"        #mt5 服务器地址
    user= 52280144               #mt5 账户
    pwd= "pO7x@QvxO@j0Bv"                #密码
    subSymbol= "USDCNH"  # mt5 交易标的
    fillType = 1        #0 = 全成或撤  1 =成交剩余撤   2= 被动挂单(限价)    3= 成交,剩余挂单


[db]
    host="rm-bp1l09swp665a10naro.mysql.rds.aliyuncs.com"
    user="test_quant"
    pwd="ASDzxc!%40#"  # 实际为ASDzxc!@#
    charset="utf8"
	db="quant"
	table="child"
	
[zmq]
    topic="market"
    reqrspPort="tcp://127.0.0.1:30003"
