[BASE]
total_cost = 10000000
usd_rate =7.2
limit_ctp_strategy_order_numbers = 430
limit_open_close_time = 0.3
[LONG.base]
longShort = "LONG"
isRun = true
closeByStrategy = false
startSpread = 1800
rangeSpread = 100
closeSpread = 100
maxVol = 2
stopDate = [ "2025-03-12", "2025-03-20",]
stopDateTime = [ "2025-03-05T09:14:15", "2025-03-20T09:20:50",]

[LONG.op1]
symbol = "au2508"
rate = 1

[LONG.op2]
symbol = "XAUUSD"
rate = 0.3

[LONG.op3]
symbol = "USDCNH"
rate = 1

[SHORT.base]
longShort = "SHORT"
isRun = false
closeByStrategy = false
startSpread = 840
rangeSpread = 30
closeSpread = 40
maxVol = 2
stopDate = [ "2025-03-20", "2025-03-17",]
stopDateTime = [ "2025-03-20T09:10:15", "2025-03-28T13:20:50",]

[SHORT.op1]
symbol = "au2508"
rate = 1

[SHORT.op2]
symbol = "XAUUSD"
rate = 0.3

[SHORT.op3]
symbol = "USDCNH"
rate = 1
