[base]
startSpread=100
rangeSpread=20
closeSpread=10
maxVol=10                               #最大持仓
stopDate = ["2025/03/20","2025/03/20"]  #以下3者配置任一生效则停止交易
stopDateTime=["2025/03/20 09:10:15","2025/03/20 09:20:50"]

[op1]
symbol = "au2506"
rate=1                  #  表示 每个区间最多加仓   策略(100,20), 140 最多持仓 6手,如果 100,120无,则再140补齐6手

[op2]
symbol = "GOLD#"
rate = 0.2              # 每一手期货需要交易几手该标的

[op3]
symbol = "USDCNH"
rate = 0.85
