[LONG.base]
longShort = "LONG"
isRun = true
startSpread = 100
rangeSpread = 20.2
closeSpread = 10
maxVol = 2
stopDate = [ "2025-03-12", "2025-03-20",]
stopDateTime = [ "2025-03-05T09:14:15", "2025-03-20T09:20:50",]

[LONG.op1]
symbol = "au2508"
rate = 1

[LONG.op2]
symbol = "XAUUSD"
rate = 0.01

[LONG.op3]
symbol = "USDCNH"
rate = 0.01

[SHORT.base]
longShort = "SHORT"
isRun = true
startSpread = 80
rangeSpread = 50
closeSpread = 10
maxVol = 3
stopDate = [ "2025-03-20", "2025-03-17",]
stopDateTime = [ "2025-03-20T09:10:15", "2025-03-28T13:20:50",]

[SHORT.op1]
symbol = "au2508"
rate = 1

[SHORT.op2]
symbol = "XAUUSD"
rate = 0.01

[SHORT.op3]
symbol = "USDCNH"
rate = 0.02
